#pragma once

static const char* VertShaderSrcSetupMask =
"#version 330 core\n"
"in vec4 a_position;"
"in vec2 a_texCoord;"
"out vec2 v_texCoord;"
"out vec4 v_myPos;"
"uniform mat4 u_clipMatrix;"
"void main()"
"{"
"gl_Position = u_clipMatrix * a_position;"
"v_myPos = u_clipMatrix * a_position;"
"v_texCoord = a_texCoord;"
"v_texCoord.y = 1.0 - v_texCoord.y;"
"}";

static const char* FragShaderSrcSetupMask =
"#version 330 core\n"
"in vec2 v_texCoord;"
"in vec4 v_myPos;"
"out vec4 fragColor;"
"uniform sampler2D s_texture0;"
"uniform vec4 u_channelFlag;"
"uniform vec4 u_baseColor;"
"void main()"
"{"
"float isInside = "
"  step(u_baseColor.x, v_myPos.x/v_myPos.w)"
"* step(u_baseColor.y, v_myPos.y/v_myPos.w)"
"* step(v_myPos.x/v_myPos.w, u_baseColor.z)"
"* step(v_myPos.y/v_myPos.w, u_baseColor.w);"
"fragColor = u_channelFlag * texture(s_texture0, v_texCoord).a * isInside;"
"}";

static const char* VertShaderSrc =
"#version 330 core\n"
"in vec4 a_position;"
"in vec2 a_texCoord;"
"out vec2 v_texCoord;"
"uniform mat4 u_matrix;"
"void main()"
"{"
"gl_Position = u_matrix * a_position;"
"v_texCoord = a_texCoord;"
"v_texCoord.y = 1.0 - v_texCoord.y;"
"}";

static const char* VertShaderSrcMasked =
"#version 330 core\n"
"in vec4 a_position;"
"in vec2 a_texCoord;"
"out vec2 v_texCoord;"
"out vec4 v_clipPos;"
"uniform mat4 u_matrix;"
"uniform mat4 u_clipMatrix;"
"void main()"
"{"
"gl_Position = u_matrix * a_position;"
"v_clipPos = u_clipMatrix * a_position;"
"v_texCoord = a_texCoord;"
"v_texCoord.y = 1.0 - v_texCoord.y;"
"}";

static const char* FragShaderSrc =
"#version 330 core\n"
"in vec2 v_texCoord;"
"out vec4 fragColor;"
"uniform sampler2D s_texture0;"
"uniform vec4 u_baseColor;"
"uniform vec4 u_multiplyColor;"
"uniform vec4 u_screenColor;"
"void main()"
"{"
"vec4 texColor = texture(s_texture0, v_texCoord);"
"texColor.rgb = texColor.rgb * u_multiplyColor.rgb;"
"texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);"
"vec4 color = texColor * u_baseColor;"
"fragColor = vec4(color.rgb * color.a, color.a);"
"}";

static const char* FragShaderSrcPremultipliedAlpha =
"#version 330 core\n"
"in vec2 v_texCoord;"
"out vec4 fragColor;"
"uniform sampler2D s_texture0;"
"uniform vec4 u_baseColor;"
"uniform vec4 u_multiplyColor;"
"uniform vec4 u_screenColor;"
"void main()"
"{"
"vec4 texColor = texture(s_texture0, v_texCoord);"
"texColor.rgb = texColor.rgb * u_multiplyColor.rgb;"
"texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);"
"fragColor = texColor * u_baseColor;"
"}";

static const char* FragShaderSrcMask =
"#version 330 core\n"
"in vec2 v_texCoord;"
"in vec4 v_clipPos;"
"out vec4 fragColor;"
"uniform sampler2D s_texture0;"
"uniform sampler2D s_texture1;"
"uniform vec4 u_channelFlag;"
"uniform vec4 u_baseColor;"
"uniform vec4 u_multiplyColor;"
"uniform vec4 u_screenColor;"
"void main()"
"{"
"vec4 texColor = texture(s_texture0, v_texCoord);"
"texColor.rgb = texColor.rgb * u_multiplyColor.rgb;"
"texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);"
"vec4 col_formask = texColor * u_baseColor;"
"col_formask.rgb = col_formask.rgb * col_formask.a;"
"vec2 clipUv = vec2(v_clipPos.x / v_clipPos.w, v_clipPos.y / v_clipPos.w);"
"vec4 clipMask = (1.0 - texture(s_texture1, clipUv)) * u_channelFlag;"
"float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;"
"col_formask = col_formask * maskVal;"
"fragColor = col_formask;"
"}";

static const char* FragShaderSrcMaskInverted =
"#version 330 core\n"
"in vec2 v_texCoord;"
"in vec4 v_clipPos;"
"out vec4 fragColor;"
"uniform sampler2D s_texture0;"
"uniform sampler2D s_texture1;"
"uniform vec4 u_channelFlag;"
"uniform vec4 u_baseColor;"
"uniform vec4 u_multiplyColor;"
"uniform vec4 u_screenColor;"
"void main()"
"{"
"vec4 texColor = texture(s_texture0, v_texCoord);"
"texColor.rgb = texColor.rgb * u_multiplyColor.rgb;"
"texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);"
"vec4 col_formask = texColor * u_baseColor;"
"col_formask.rgb = col_formask.rgb * col_formask.a;"
"vec2 clipUv = vec2(v_clipPos.x / v_clipPos.w, v_clipPos.y / v_clipPos.w);"
"vec4 clipMask = (1.0 - texture(s_texture1, clipUv)) * u_channelFlag;"
"float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;"
"col_formask = col_formask * (1.0 - maskVal);"
"fragColor = col_formask;"
"}";

static const char* FragShaderSrcMaskPremultipliedAlpha =
"#version 330 core\n"
"in vec2 v_texCoord;"
"in vec4 v_clipPos;"
"out vec4 fragColor;"
"uniform sampler2D s_texture0;"
"uniform sampler2D s_texture1;"
"uniform vec4 u_channelFlag;"
"uniform vec4 u_baseColor;"
"uniform vec4 u_multiplyColor;"
"uniform vec4 u_screenColor;"
"void main()"
"{"
"vec4 texColor = texture(s_texture0, v_texCoord);"
"texColor.rgb = texColor.rgb * u_multiplyColor.rgb;"
"texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);"
"vec4 col_formask = texColor * u_baseColor;"
"vec2 clipUv = vec2(v_clipPos.x / v_clipPos.w, v_clipPos.y / v_clipPos.w);"
"vec4 clipMask = (1.0 - texture(s_texture1, clipUv)) * u_channelFlag;"
"float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;"
"col_formask = col_formask * maskVal;"
"fragColor = col_formask;"
"}";

static const char* FragShaderSrcMaskInvertedPremultipliedAlpha =
"#version 330 core\n"
"in vec2 v_texCoord;"
"in vec4 v_clipPos;"
"out vec4 fragColor;"
"uniform sampler2D s_texture0;"
"uniform sampler2D s_texture1;"
"uniform vec4 u_channelFlag;"
"uniform vec4 u_baseColor;"
"uniform vec4 u_multiplyColor;"
"uniform vec4 u_screenColor;"
"void main()"
"{"
"vec4 texColor = texture(s_texture0, v_texCoord);"
"texColor.rgb = texColor.rgb * u_multiplyColor.rgb;"
"texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);"
"vec4 col_formask = texColor * u_baseColor;"
"vec2 clipUv = vec2(v_clipPos.x / v_clipPos.w, v_clipPos.y / v_clipPos.w);"
"vec4 clipMask = (1.0 - texture(s_texture1, clipUv)) * u_channelFlag;"
"float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;"
"col_formask = col_formask * (1.0 - maskVal);"
"fragColor = col_formask;"
"}";
